[package]
name = "vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
clap = { version = "4.3.22", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.20"
nom = "7.1.3"
